/** Generate `src/version.ts` from the package version in `package.json`. */

import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const packageDir = process.cwd();
const raw: unknown = JSON.parse(readFileSync(path.join(packageDir, 'package.json'), 'utf8'));

if (typeof raw !== 'object' || raw === null || !('version' in raw) || typeof raw.version !== 'string') {
  throw new Error('package.json must contain a "version" string');
}

const content = `// Generated by config/generateVersion.ts — do not edit\nexport const VERSION = '${raw.version}';\n`;
writeFileSync(path.join(packageDir, 'src', 'version.ts'), content);
