import { describe, expect, it } from 'vitest';

import { detectBundlerOutput } from '../detectBundlerOutput.ts';

const HAND_WRITTEN = [
  "import path from 'node:path';",
  '',
  '/** Joins a directory and a name. */',
  'export function joinName(dir: string, name: string): string {',
  '  return path.join(dir, name);',
  '}',
  '',
].join('\n');

describe(detectBundlerOutput, () => {
  it('judges a minified source by its line density', () => {
    const minified = `${'var a=1;'.repeat(200)}\n${'b();'.repeat(100)}\n`;

    expect(detectBundlerOutput(minified)).toBe('density');
  });

  it('judges an unminified esbuild bundle by its runtime helpers', () => {
    const bundle = [
      "import { createRequire } from 'node:module';",
      'var __create = Object.create;',
      'var __defProp = Object.defineProperty;',
      '',
      '// src/index.ts',
      'export const x = 1;',
      '',
    ].join('\n');

    expect(detectBundlerOutput(bundle)).toBe('header');
  });

  it('judges a webpack bundle by its bootstrap', () => {
    const bundle = ['/******/ (() => { // webpackBootstrap', '/******/ \tvar __webpack_modules__ = ({});', ''].join(
      '\n',
    );

    expect(detectBundlerOutput(bundle)).toBe('header');
  });

  it('judges a source by an @generated marker on an opening comment line', () => {
    expect(detectBundlerOutput(`/** @noformat -- @generated. Do not edit. */\n${HAND_WRITTEN}`)).toBe('header');
    expect(detectBundlerOutput(`// @generated by protoc\n${HAND_WRITTEN}`)).toBe('header');
  });

  it('passes a file quoting a bundler helper in a string or a comment among its opening lines', () => {
    expect(
      detectBundlerOutput(`const HELPER = 'var __defProp = Object.defineProperty';\n${HAND_WRITTEN}`),
    ).toBeUndefined();
    expect(detectBundlerOutput(`// var __commonJS = (cb) => cb;\n${HAND_WRITTEN}`)).toBeUndefined();
  });

  it('passes a hand-written module', () => {
    expect(detectBundlerOutput(HAND_WRITTEN)).toBeUndefined();
  });

  it('passes a short file whose one long line would otherwise dominate the mean', () => {
    expect(detectBundlerOutput(`export const message = '${'x'.repeat(400)}';\n`)).toBeUndefined();
  });

  it('passes a file naming a bundler helper only below the opening lines', () => {
    const lines = Array.from({ length: 20 }, (_, index) => `const line${index} = ${index};`);
    lines.push("const pattern = 'var __defProp = Object.defineProperty';");

    expect(detectBundlerOutput(lines.join('\n'))).toBeUndefined();
  });

  it('passes a file mentioning @generated in code or below the opening lines', () => {
    expect(detectBundlerOutput(`const tag = '@generated';\n${HAND_WRITTEN}`)).toBeUndefined();
    expect(detectBundlerOutput(`${HAND_WRITTEN}// @generated\n`)).toBeUndefined();
  });

  it('counts CRLF terminators as line ends rather than as characters', () => {
    const lines = Array.from({ length: 50 }, () => 'x'.repeat(250));

    expect(detectBundlerOutput(`${lines.join('\r\n')}\r\n`)).toBeUndefined();
  });

  it('passes a file of blank lines and an empty file', () => {
    expect(detectBundlerOutput('\n'.repeat(2_000))).toBeUndefined();
    expect(detectBundlerOutput('')).toBeUndefined();
  });
});
