# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Code quality checks

# Note: This workflow will be automatically skipped if the commit message includes
# any of the following strings: [skip ci], [ci skip], [no ci], [skip actions], or [actions skip]

on:
  push:
    branches:
      - main
      - next

  pull_request:
    branches:
      - main
      - next

  workflow_dispatch: {}

jobs:
  code-quality:
    uses: williamthorsen/.github/.github/workflows/code-quality-pnpm-workflow.yaml@v5
    with:
      check-command: pnpm exec nmr ci
      node-version: '24.14.1'
