# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Create GitHub Release

on:
  push:
    tags:
      - '*-v[0-9]*.[0-9]*.[0-9]*'

permissions:
  contents: write

jobs:
  create-github-release:
    uses: williamthorsen/node-monorepo-tools/.github/workflows/create-github-release.reusable.yaml@workflow/create-github-release-v1
    with:
      tag: ${{ github.ref_name }}
